// ============================================================================
// stark::verifier — Verifies zk-STARK proofs for balance transfers
//
// The verifier checks a proof against public inputs (final balances) without
// knowing any private witness data (initial balances, transfer amount).
// ============================================================================

use winterfell::{
    crypto::{DefaultRandomCoin, MerkleTree},
    math::fields::f128::BaseElement,
    AcceptableOptions, Proof, VerifierError,
};

use winterfell::crypto::hashers::Blake3_256;

use super::air::BalanceTransferAir;
use super::BalanceTransferInputs;

type StarkHasher = Blake3_256<BaseElement>;

// ============================================================================
// PUBLIC API
// ============================================================================

/// Verify a zk-STARK proof for a balance transfer.
///
/// # Arguments
/// * `proof` — The STARK proof generated by `prove_balance_transfer`
/// * `public_inputs` — The claimed final balances (only thing the verifier sees)
///
/// # Returns
/// * `Ok(())` if the proof is valid
/// * `Err(VerifierError)` if the proof is invalid or tampered with
pub fn verify_balance_transfer(
    proof: Proof,
    public_inputs: BalanceTransferInputs,
) -> Result<(), VerifierError> {
    // Accept any proof options that match the ones used during proving
    let acceptable_options =
        AcceptableOptions::OptionSet(vec![proof.options().clone()]);

    winterfell::verify::<
        BalanceTransferAir,
        StarkHasher,
        DefaultRandomCoin<StarkHasher>,
        MerkleTree<StarkHasher>,
    >(proof, public_inputs, &acceptable_options)
}
